// ===== LE VOCABULAIRE =====
// Chaque ligne = [ "français", "anglais", "néerlandais" ]
// Pour ajouter un mot : copie une ligne dans le bon thème et modifie-la.
// Pour ajouter un thème : copie un bloc { nom: ..., mots: [ ... ] }.
// Attention : chaque mot français doit être unique (il sert à retenir ton niveau).

const THEMES = [

{ nom: "👋 Bonjour & politesse", mots: [
  ["bonjour",              "hello",                 "hallo"],
  ["salut",                "hi",                    "hoi"],
  ["bonsoir",              "good evening",          "goedenavond"],
  ["bonne nuit",           "good night",            "welterusten"],
  ["au revoir",            "goodbye",               "tot ziens"],
  ["à bientôt",            "see you soon",          "tot gauw"],
  ["à demain",             "see you tomorrow",      "tot morgen"],
  ["merci",                "thank you",             "dank je"],
  ["merci beaucoup",       "thank you very much",   "heel erg bedankt"],
  ["s'il te plaît",        "please",                "alsjeblieft"],
  ["s'il vous plaît",      "please (polite)",       "alstublieft"],
  ["de rien",              "you're welcome",        "graag gedaan"],
  ["pardon",               "excuse me",             "pardon"],
  ["désolé",               "sorry",                 "sorry"],
  ["oui",                  "yes",                   "ja"],
  ["non",                  "no",                    "nee"],
  ["peut-être",            "maybe",                 "misschien"],
  ["d'accord",             "okay",                  "oké"],
  ["comment ça va ?",      "how are you?",          "hoe gaat het?"],
  ["ça va bien",           "I'm fine",              "het gaat goed"],
  ["et toi ?",             "and you?",              "en jij?"],
  ["enchanté",             "nice to meet you",      "aangenaam"],
  ["bienvenue",            "welcome",               "welkom"],
  ["bonne journée",        "have a nice day",       "fijne dag"],
  ["bon appétit",          "enjoy your meal",       "eet smakelijk"],
  ["félicitations",        "congratulations",       "gefeliciteerd"],
  ["bonne chance",         "good luck",             "succes"]
]},

{ nom: "💬 Phrases de tous les jours", mots: [
  ["je m'appelle...",             "my name is...",            "ik heet..."],
  ["comment tu t'appelles ?",     "what's your name?",        "hoe heet je?"],
  ["j'ai ... ans",                "I am ... years old",       "ik ben ... jaar oud"],
  ["où habites-tu ?",             "where do you live?",       "waar woon je?"],
  ["j'habite à...",               "I live in...",             "ik woon in..."],
  ["je ne comprends pas",         "I don't understand",       "ik begrijp het niet"],
  ["tu peux répéter ?",           "can you repeat that?",     "kun je dat herhalen?"],
  ["parle plus lentement",        "speak more slowly",        "spreek langzamer"],
  ["je ne sais pas",              "I don't know",             "ik weet het niet"],
  ["comment dit-on ... ?",        "how do you say ...?",      "hoe zeg je ...?"],
  ["que veut dire ... ?",         "what does ... mean?",      "wat betekent ...?"],
  ["j'ai faim",                   "I'm hungry",               "ik heb honger"],
  ["j'ai soif",                   "I'm thirsty",              "ik heb dorst"],
  ["je suis fatigué",             "I'm tired",                "ik ben moe"],
  ["j'aime...",                   "I like...",                "ik hou van..."],
  ["je n'aime pas...",            "I don't like...",          "ik hou niet van..."],
  ["où sont les toilettes ?",     "where is the toilet?",     "waar is de wc?"],
  ["combien ça coûte ?",          "how much is it?",          "hoeveel kost het?"],
  ["quelle heure est-il ?",       "what time is it?",         "hoe laat is het?"],
  ["à quelle heure ?",            "at what time?",            "om hoe laat?"],
  ["j'ai besoin d'aide",          "I need help",              "ik heb hulp nodig"],
  ["je suis d'accord",            "I agree",                  "ik ben het ermee eens"],
  ["je voudrais...",              "I would like...",          "ik wil graag..."],
  ["il fait beau",                "the weather is nice",      "het is mooi weer"],
  ["il pleut",                    "it's raining",             "het regent"],
  ["il fait chaud",               "it's hot",                 "het is warm"],
  ["il fait froid",               "it's cold",                "het is koud"],
  ["qu'est-ce que c'est ?",       "what is it?",              "wat is dat?"],
  ["c'est bon",                   "it's good",                "het is goed"],
  ["pas de problème",             "no problem",               "geen probleem"]
]},

{ nom: "❓ Petits mots utiles", mots: [
  ["qui",            "who",          "wie"],
  ["quoi",           "what",         "wat"],
  ["où",             "where",        "waar"],
  ["quand",          "when",         "wanneer"],
  ["pourquoi",       "why",          "waarom"],
  ["comment",        "how",          "hoe"],
  ["combien",        "how much",     "hoeveel"],
  ["quel",           "which",        "welke"],
  ["parce que",      "because",      "omdat"],
  ["et",             "and",          "en"],
  ["ou",             "or",           "of"],
  ["mais",           "but",          "maar"],
  ["avec",           "with",         "met"],
  ["sans",           "without",      "zonder"],
  ["pour",           "for",          "voor"],
  ["dans",           "in",           "in"],
  ["sur",            "on",           "op"],
  ["sous",           "under",        "onder"],
  ["derrière",       "behind",       "achter"],
  ["à côté de",      "next to",      "naast"],
  ["entre",          "between",      "tussen"],
  ["très",           "very",         "heel"],
  ["aussi",          "also",         "ook"],
  ["encore",         "again",        "opnieuw"],
  ["beaucoup",       "a lot",        "veel"],
  ["un peu",         "a little",     "een beetje"],
  ["ici",            "here",         "hier"],
  ["là-bas",         "there",        "daar"],
  ["maintenant",     "now",          "nu"],
  ["toujours",       "always",       "altijd"],
  ["jamais",         "never",        "nooit"],
  ["souvent",        "often",        "vaak"],
  ["parfois",        "sometimes",    "soms"],
  ["déjà",           "already",      "al"],
  ["bientôt",        "soon",         "binnenkort"],
  ["tout",           "everything",   "alles"],
  ["rien",           "nothing",      "niets"],
  ["quelqu'un",      "someone",      "iemand"],
  ["personne",       "nobody",       "niemand"]
]},

{ nom: "🙋 Je, tu, il...", mots: [
  ["je",             "I",                "ik"],
  ["tu",             "you",              "jij"],
  ["il",             "he",               "hij"],
  ["elle",           "she",              "zij"],
  ["nous",           "we",               "wij"],
  ["vous",           "you (plural)",     "jullie"],
  ["ils / elles",    "they",             "zij (meervoud)"],
  ["mon / ma",       "my",               "mijn"],
  ["ton / ta",       "your",             "jouw"],
  ["son (à lui)",    "his",              "zijn"],
  ["son (à elle)",   "her",              "haar"],
  ["notre",          "our",              "ons / onze"],
  ["leur",           "their",            "hun"]
]},

{ nom: "🔢 Nombres", mots: [
  ["zéro",           "zero",         "nul"],
  ["un",             "one",          "een"],
  ["deux",           "two",          "twee"],
  ["trois",          "three",        "drie"],
  ["quatre",         "four",         "vier"],
  ["cinq",           "five",         "vijf"],
  ["six",            "six",          "zes"],
  ["sept",           "seven",        "zeven"],
  ["huit",           "eight",        "acht"],
  ["neuf",           "nine",         "negen"],
  ["dix",            "ten",          "tien"],
  ["onze",           "eleven",       "elf"],
  ["douze",          "twelve",       "twaalf"],
  ["treize",         "thirteen",     "dertien"],
  ["quatorze",       "fourteen",     "veertien"],
  ["quinze",         "fifteen",      "vijftien"],
  ["seize",          "sixteen",      "zestien"],
  ["dix-sept",       "seventeen",    "zeventien"],
  ["dix-huit",       "eighteen",     "achttien"],
  ["dix-neuf",       "nineteen",     "negentien"],
  ["vingt",          "twenty",       "twintig"],
  ["trente",         "thirty",       "dertig"],
  ["quarante",       "forty",        "veertig"],
  ["cinquante",      "fifty",        "vijftig"],
  ["soixante",       "sixty",        "zestig"],
  ["soixante-dix",   "seventy",      "zeventig"],
  ["quatre-vingts",  "eighty",       "tachtig"],
  ["quatre-vingt-dix","ninety",      "negentig"],
  ["cent",           "one hundred",  "honderd"],
  ["mille",          "one thousand", "duizend"],
  ["premier",        "first",        "eerste"],
  ["deuxième",       "second",       "tweede"],
  ["dernier",        "last",         "laatste"]
]},

{ nom: "📅 Jours, mois & temps", mots: [
  ["lundi",          "Monday",       "maandag"],
  ["mardi",          "Tuesday",      "dinsdag"],
  ["mercredi",       "Wednesday",    "woensdag"],
  ["jeudi",          "Thursday",     "donderdag"],
  ["vendredi",       "Friday",       "vrijdag"],
  ["samedi",         "Saturday",     "zaterdag"],
  ["dimanche",       "Sunday",       "zondag"],
  ["janvier",        "January",      "januari"],
  ["février",        "February",     "februari"],
  ["mars",           "March",        "maart"],
  ["avril",          "April",        "april"],
  ["mai",            "May",          "mei"],
  ["juin",           "June",         "juni"],
  ["juillet",        "July",         "juli"],
  ["août",           "August",       "augustus"],
  ["septembre",      "September",    "september"],
  ["octobre",        "October",      "oktober"],
  ["novembre",       "November",     "november"],
  ["décembre",       "December",     "december"],
  ["aujourd'hui",    "today",        "vandaag"],
  ["demain",         "tomorrow",     "morgen"],
  ["hier",           "yesterday",    "gisteren"],
  ["le matin",       "the morning",  "de ochtend"],
  ["l'après-midi",   "the afternoon","de middag"],
  ["le soir",        "the evening",  "de avond"],
  ["la nuit",        "the night",    "de nacht"],
  ["le jour",        "the day",      "de dag"],
  ["la semaine",     "the week",     "de week"],
  ["le mois",        "the month",    "de maand"],
  ["l'année",        "the year",     "het jaar"],
  ["l'heure",        "the hour",     "het uur"],
  ["la minute",      "the minute",   "de minuut"],
  ["le week-end",    "the weekend",  "het weekend"],
  ["le printemps",   "spring",       "de lente"],
  ["l'été",          "summer",       "de zomer"],
  ["l'automne",      "autumn",       "de herfst"],
  ["l'hiver",        "winter",       "de winter"]
]},

{ nom: "🎨 Couleurs", mots: [
  ["rouge",          "red",          "rood"],
  ["bleu",           "blue",         "blauw"],
  ["vert",           "green",        "groen"],
  ["jaune",          "yellow",       "geel"],
  ["orange",         "orange",       "oranje"],
  ["violet",         "purple",       "paars"],
  ["rose",           "pink",         "roze"],
  ["noir",           "black",        "zwart"],
  ["blanc",          "white",        "wit"],
  ["gris",           "grey",         "grijs"],
  ["marron",         "brown",        "bruin"],
  ["clair",          "light",        "licht"],
  ["foncé",          "dark",         "donker"]
]},

{ nom: "👨‍👩‍👧 Famille & gens", mots: [
  ["la famille",         "the family",       "de familie"],
  ["la mère",            "the mother",       "de moeder"],
  ["le père",            "the father",       "de vader"],
  ["les parents",        "the parents",      "de ouders"],
  ["le frère",           "the brother",      "de broer"],
  ["la sœur",            "the sister",       "de zus"],
  ["le fils",            "the son",          "de zoon"],
  ["la fille (enfant)",  "the daughter",     "de dochter"],
  ["le grand-père",      "the grandfather",  "de opa"],
  ["la grand-mère",      "the grandmother",  "de oma"],
  ["l'oncle",            "the uncle",        "de oom"],
  ["la tante",           "the aunt",         "de tante"],
  ["le cousin",          "the cousin (boy)", "de neef"],
  ["la cousine",         "the cousin (girl)","de nicht"],
  ["le bébé",            "the baby",         "de baby"],
  ["l'enfant",           "the child",        "het kind"],
  ["l'homme",            "the man",          "de man"],
  ["la femme",           "the woman",        "de vrouw"],
  ["le garçon",          "the boy",          "de jongen"],
  ["la fille",           "the girl",         "het meisje"],
  ["l'ami",              "the friend (boy)", "de vriend"],
  ["l'amie",             "the friend (girl)","de vriendin"],
  ["le voisin",          "the neighbour",    "de buurman"],
  ["les gens",           "the people",       "de mensen"]
]},

{ nom: "🧍 Corps & santé", mots: [
  ["la tête",            "the head",         "het hoofd"],
  ["les cheveux",        "the hair",         "het haar"],
  ["les yeux",           "the eyes",         "de ogen"],
  ["l'oreille",          "the ear",          "het oor"],
  ["le nez",             "the nose",         "de neus"],
  ["la bouche",          "the mouth",        "de mond"],
  ["les dents",          "the teeth",        "de tanden"],
  ["le cou",             "the neck",         "de nek"],
  ["le bras",            "the arm",          "de arm"],
  ["la main",            "the hand",         "de hand"],
  ["le doigt",           "the finger",       "de vinger"],
  ["le ventre",          "the belly",        "de buik"],
  ["le dos",             "the back",         "de rug"],
  ["la jambe",           "the leg",          "het been"],
  ["le pied",            "the foot",         "de voet"],
  ["le cœur",            "the heart",        "het hart"],
  ["malade",             "sick",             "ziek"],
  ["le médecin",         "the doctor",       "de dokter"],
  ["j'ai mal à la tête", "I have a headache","ik heb hoofdpijn"],
  ["la douleur",         "the pain",         "de pijn"],
  ["le médicament",      "the medicine",     "het medicijn"],
  ["l'hôpital",          "the hospital",     "het ziekenhuis"]
]},

{ nom: "🍎 Nourriture & boissons", mots: [
  ["le pain",            "bread",            "het brood"],
  ["le beurre",          "butter",           "de boter"],
  ["le fromage",         "cheese",           "de kaas"],
  ["le lait",            "milk",             "de melk"],
  ["l'eau",              "water",            "het water"],
  ["le café",            "coffee",           "de koffie"],
  ["le thé",             "tea",              "de thee"],
  ["le jus",             "juice",            "het sap"],
  ["l'œuf",              "the egg",          "het ei"],
  ["la viande",          "meat",             "het vlees"],
  ["le poulet",          "chicken",          "de kip"],
  ["le poisson",         "fish",             "de vis"],
  ["le riz",             "rice",             "de rijst"],
  ["les pâtes",          "pasta",            "de pasta"],
  ["la pomme de terre",  "the potato",       "de aardappel"],
  ["les frites",         "fries",            "de friet"],
  ["le légume",          "the vegetable",    "de groente"],
  ["le fruit",           "fruit",            "het fruit"],
  ["la pomme",           "the apple",        "de appel"],
  ["la banane",          "the banana",       "de banaan"],
  ["l'orange",           "the orange",       "de sinaasappel"],
  ["la fraise",          "the strawberry",   "de aardbei"],
  ["la tomate",          "the tomato",       "de tomaat"],
  ["la salade",          "the salad",        "de salade"],
  ["la soupe",           "soup",             "de soep"],
  ["le sucre",           "sugar",            "de suiker"],
  ["le sel",             "salt",             "het zout"],
  ["le gâteau",          "the cake",         "de taart"],
  ["le chocolat",        "chocolate",        "de chocolade"],
  ["la glace",           "ice cream",        "het ijs"],
  ["le petit-déjeuner",  "breakfast",        "het ontbijt"],
  ["le déjeuner",        "lunch",            "de lunch"],
  ["le dîner",           "dinner",           "het avondeten"],
  ["le repas",           "the meal",         "de maaltijd"],
  ["délicieux",          "delicious",        "lekker"]
]},

{ nom: "🛒 Magasin & restaurant", mots: [
  ["le magasin",         "the shop",         "de winkel"],
  ["le supermarché",     "the supermarket",  "de supermarkt"],
  ["l'argent",           "money",            "het geld"],
  ["cher",               "expensive",        "duur"],
  ["pas cher",           "cheap",            "goedkoop"],
  ["payer",              "to pay",           "betalen"],
  ["la carte bancaire",  "the bank card",    "de bankpas"],
  ["la caisse",          "the checkout",     "de kassa"],
  ["le sac",             "the bag",          "de tas"],
  ["ouvert",             "open",             "open"],
  ["fermé",              "closed",           "gesloten"],
  ["le menu",            "the menu",         "de menukaart"],
  ["l'addition",         "the bill",         "de rekening"],
  ["le serveur",         "the waiter",       "de ober"]
]},

{ nom: "🏠 Maison", mots: [
  ["la maison",          "the house",        "het huis"],
  ["l'appartement",      "the apartment",    "het appartement"],
  ["la chambre",         "the bedroom",      "de slaapkamer"],
  ["la cuisine",         "the kitchen",      "de keuken"],
  ["la salle de bain",   "the bathroom",     "de badkamer"],
  ["le salon",           "the living room",  "de woonkamer"],
  ["les toilettes",      "the toilet",       "de wc"],
  ["la porte",           "the door",         "de deur"],
  ["la fenêtre",         "the window",       "het raam"],
  ["la table",           "the table",        "de tafel"],
  ["la chaise",          "the chair",        "de stoel"],
  ["le lit",             "the bed",          "het bed"],
  ["le canapé",          "the sofa",         "de bank"],
  ["la clé",             "the key",          "de sleutel"],
  ["la lampe",           "the lamp",         "de lamp"],
  ["le frigo",           "the fridge",       "de koelkast"],
  ["la télé",            "the TV",           "de tv"],
  ["le téléphone",       "the phone",        "de telefoon"],
  ["l'ordinateur",       "the computer",     "de computer"],
  ["le jardin",          "the garden",       "de tuin"],
  ["l'escalier",         "the stairs",       "de trap"],
  ["le mur",             "the wall",         "de muur"]
]},

{ nom: "🏫 École", mots: [
  ["l'école",            "the school",       "de school"],
  ["la classe",          "the class",        "de klas"],
  ["le professeur",      "the teacher",      "de leraar"],
  ["l'élève",            "the pupil",        "de leerling"],
  ["le livre",           "the book",         "het boek"],
  ["le cahier",          "the notebook",     "het schrift"],
  ["le stylo",           "the pen",          "de pen"],
  ["le crayon",          "the pencil",       "het potlood"],
  ["la gomme",           "the eraser",       "de gum"],
  ["la règle",           "the ruler",        "de liniaal"],
  ["le sac à dos",       "the backpack",     "de rugzak"],
  ["le tableau",         "the board",        "het bord"],
  ["la leçon",           "the lesson",       "de les"],
  ["les devoirs",        "the homework",     "het huiswerk"],
  ["le contrôle",        "the test",         "de toets"],
  ["la question",        "the question",     "de vraag"],
  ["la réponse",         "the answer",       "het antwoord"],
  ["le mot",             "the word",         "het woord"],
  ["la phrase",          "the sentence",     "de zin"],
  ["la récréation",      "the break",        "de pauze"],
  ["les maths",          "maths",            "wiskunde"],
  ["l'anglais",          "English",          "Engels"],
  ["le néerlandais",     "Dutch",            "Nederlands"],
  ["le français",        "French",           "Frans"]
]},

{ nom: "🏃 Verbes du quotidien", mots: [
  ["être",               "to be",            "zijn"],
  ["avoir",              "to have",          "hebben"],
  ["aller",              "to go",            "gaan"],
  ["venir",              "to come",          "komen"],
  ["faire",              "to do / to make",  "doen / maken"],
  ["dire",               "to say",           "zeggen"],
  ["parler",             "to speak",         "spreken"],
  ["manger",             "to eat",           "eten"],
  ["boire",              "to drink",         "drinken"],
  ["dormir",             "to sleep",         "slapen"],
  ["se lever",           "to get up",        "opstaan"],
  ["travailler",         "to work",          "werken"],
  ["jouer",              "to play",          "spelen"],
  ["lire",               "to read",          "lezen"],
  ["écrire",             "to write",         "schrijven"],
  ["écouter",            "to listen",        "luisteren"],
  ["regarder",           "to watch",         "kijken"],
  ["voir",               "to see",           "zien"],
  ["entendre",           "to hear",          "horen"],
  ["savoir",             "to know",          "weten"],
  ["connaître",          "to know (someone)","kennen"],
  ["pouvoir",            "can",              "kunnen"],
  ["vouloir",            "to want",          "willen"],
  ["devoir",             "must",             "moeten"],
  ["aimer",              "to love",          "houden van"],
  ["donner",             "to give",          "geven"],
  ["prendre",            "to take",          "nemen"],
  ["ouvrir",             "to open",          "openen"],
  ["fermer",             "to close",         "sluiten"],
  ["commencer",          "to start",         "beginnen"],
  ["finir",              "to finish",        "afmaken"],
  ["attendre",           "to wait",          "wachten"],
  ["chercher",           "to look for",      "zoeken"],
  ["trouver",            "to find",          "vinden"],
  ["aider",              "to help",          "helpen"],
  ["apprendre",          "to learn",         "leren"],
  ["comprendre",         "to understand",    "begrijpen"],
  ["penser",             "to think",         "denken"],
  ["habiter",            "to live",          "wonen"],
  ["marcher",            "to walk",          "lopen"],
  ["courir",             "to run",           "rennen"],
  ["cuisiner",           "to cook",          "koken"],
  ["se laver",           "to wash (yourself)","zich wassen"],
  ["s'habiller",         "to get dressed",   "zich aankleden"],
  ["appeler (téléphone)","to call",          "bellen"],
  ["oublier",            "to forget",        "vergeten"],
  ["se souvenir",        "to remember",      "zich herinneren"],
  ["rester",             "to stay",          "blijven"],
  ["partir",             "to leave",         "vertrekken"],
  ["arriver",            "to arrive",        "aankomen"],
  ["utiliser",           "to use",           "gebruiken"],
  ["mettre",             "to put",           "zetten"]
]},

{ nom: "😊 Décrire (adjectifs)", mots: [
  ["grand",              "big",              "groot"],
  ["petit",              "small",            "klein"],
  ["long",               "long",             "lang"],
  ["court",              "short",            "kort"],
  ["nouveau",            "new",              "nieuw"],
  ["vieux",              "old",              "oud"],
  ["jeune",              "young",            "jong"],
  ["beau",               "beautiful",        "mooi"],
  ["bon",                "good",             "goed"],
  ["mauvais",            "bad",              "slecht"],
  ["chaud",              "warm",             "warm"],
  ["froid",              "cold",             "koud"],
  ["facile",             "easy",             "makkelijk"],
  ["difficile",          "difficult",        "moeilijk"],
  ["rapide",             "fast",             "snel"],
  ["lent",               "slow",             "langzaam"],
  ["content",            "happy",            "blij"],
  ["triste",             "sad",              "verdrietig"],
  ["gentil",             "kind",             "aardig"],
  ["drôle",              "funny",            "grappig"],
  ["intéressant",        "interesting",      "interessant"],
  ["ennuyeux",           "boring",           "saai"],
  ["fort",               "strong",           "sterk"],
  ["plein",              "full",             "vol"],
  ["vide",               "empty",            "leeg"],
  ["propre",             "clean",            "schoon"],
  ["sale",               "dirty",            "vies"],
  ["important",          "important",        "belangrijk"],
  ["prêt",               "ready",            "klaar"],
  ["occupé",             "busy",             "bezig"],
  ["libre",              "free",             "vrij"],
  ["vrai",               "true",             "waar"],
  ["faux",               "wrong",            "fout"]
]},

{ nom: "🌦️ Météo & nature", mots: [
  ["le temps (météo)",   "the weather",      "het weer"],
  ["le soleil",          "the sun",          "de zon"],
  ["la pluie",           "the rain",         "de regen"],
  ["la neige",           "the snow",         "de sneeuw"],
  ["le vent",            "the wind",         "de wind"],
  ["le nuage",           "the cloud",        "de wolk"],
  ["le ciel",            "the sky",          "de lucht"],
  ["la mer",             "the sea",          "de zee"],
  ["la plage",           "the beach",        "het strand"],
  ["la montagne",        "the mountain",     "de berg"],
  ["la forêt",           "the forest",       "het bos"],
  ["l'arbre",            "the tree",         "de boom"],
  ["la fleur",           "the flower",       "de bloem"],
  ["la rivière",         "the river",        "de rivier"]
]},

{ nom: "🐶 Animaux", mots: [
  ["le chien",           "the dog",          "de hond"],
  ["le chat",            "the cat",          "de kat"],
  ["l'oiseau",           "the bird",         "de vogel"],
  ["le cheval",          "the horse",        "het paard"],
  ["la vache",           "the cow",          "de koe"],
  ["le cochon",          "the pig",          "het varken"],
  ["le mouton",          "the sheep",        "het schaap"],
  ["la souris",          "the mouse",        "de muis"],
  ["le lapin",           "the rabbit",       "het konijn"],
  ["le lion",            "the lion",         "de leeuw"],
  ["l'ours",             "the bear",         "de beer"],
  ["le serpent",         "the snake",        "de slang"]
]},

{ nom: "🚲 Ville & transports", mots: [
  ["la ville",           "the city",         "de stad"],
  ["la rue",             "the street",       "de straat"],
  ["la voiture",         "the car",          "de auto"],
  ["le vélo",            "the bike",         "de fiets"],
  ["le bus",             "the bus",          "de bus"],
  ["le train",           "the train",        "de trein"],
  ["l'avion",            "the plane",        "het vliegtuig"],
  ["la gare",            "the station",      "het station"],
  ["l'arrêt de bus",     "the bus stop",     "de bushalte"],
  ["le billet",          "the ticket",       "het kaartje"],
  ["à gauche",           "on the left",      "links"],
  ["à droite",           "on the right",     "rechts"],
  ["tout droit",         "straight ahead",   "rechtdoor"],
  ["loin",               "far",              "ver"],
  ["près",               "near",             "dichtbij"],
  ["la banque",          "the bank",         "de bank"],
  ["la pharmacie",       "the pharmacy",     "de apotheek"],
  ["la poste",           "the post office",  "het postkantoor"],
  ["le parc",            "the park",         "het park"],
  ["l'église",           "the church",       "de kerk"],
  ["le pont",            "the bridge",       "de brug"],
  ["la place",           "the square",       "het plein"],
  ["le chemin",          "the way",          "de weg"]
]},

{ nom: "👕 Vêtements", mots: [
  ["le t-shirt",         "the T-shirt",      "het T-shirt"],
  ["le pantalon",        "the trousers",     "de broek"],
  ["la robe",            "the dress",        "de jurk"],
  ["la jupe",            "the skirt",        "de rok"],
  ["la chemise",         "the shirt",        "het overhemd"],
  ["le pull",            "the sweater",      "de trui"],
  ["la veste",           "the jacket",       "de jas"],
  ["les chaussures",     "the shoes",        "de schoenen"],
  ["les chaussettes",    "the socks",        "de sokken"],
  ["le chapeau",         "the hat",          "de hoed"],
  ["la casquette",       "the cap",          "de pet"],
  ["les lunettes",       "the glasses",      "de bril"]
]},

{ nom: "💼 Travail", mots: [
  ["le travail",         "the work",         "het werk"],
  ["le bureau",          "the office",       "het kantoor"],
  ["le collègue",        "the colleague",    "de collega"],
  ["le patron",          "the boss",         "de baas"],
  ["l'entreprise",       "the company",      "het bedrijf"],
  ["le salaire",         "the salary",       "het salaris"],
  ["la vente",           "the sale",         "de verkoop"],
  ["le client",          "the customer",     "de klant"],
  ["le marché",          "the market",       "de markt"],
  ["acheter",            "to buy",           "kopen"],
  ["vendre",             "to sell",          "verkopen"],
  ["le prix",            "the price",        "de prijs"],
  ["une réunion",        "a meeting",        "een vergadering"],
  ["demander",           "to ask",           "vragen"],
  ["répondre",           "to answer",        "antwoorden"]
]}

];
